create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  artist text not null,
  initials text not null,
  title text not null,
  description text not null,
  image text not null,
  price numeric not null default 0,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.artworks enable row level security;
drop policy if exists "Anyone can view artworks" on public.artworks;
create policy "Anyone can view artworks" on public.artworks for select using (true);
drop policy if exists "Anyone can publish artworks" on public.artworks;
create policy "Anyone can publish artworks" on public.artworks for insert with check (true);
alter table public.artworks add column if not exists artist_id uuid references auth.users(id);

create table if not exists public.artist_follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  artist_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, artist_id)
);
alter table public.artist_follows enable row level security;
drop policy if exists "Users can view follows" on public.artist_follows;
create policy "Users can view follows" on public.artist_follows for select using (true);
drop policy if exists "Users can follow artists" on public.artist_follows;
create policy "Users can follow artists" on public.artist_follows for insert with check (auth.uid() = follower_id);
drop policy if exists "Users can unfollow artists" on public.artist_follows;
create policy "Users can unfollow artists" on public.artist_follows for delete using (auth.uid() = follower_id);

create table if not exists public.artwork_likes (
  artwork_id bigint not null references public.artworks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (artwork_id, user_id)
);
alter table public.artwork_likes enable row level security;
drop policy if exists "Anyone can view likes" on public.artwork_likes;
create policy "Anyone can view likes" on public.artwork_likes for select using (true);
drop policy if exists "Users can like artwork" on public.artwork_likes;
create policy "Users can like artwork" on public.artwork_likes for insert with check (auth.uid() = user_id);
drop policy if exists "Users can remove own likes" on public.artwork_likes;
create policy "Users can remove own likes" on public.artwork_likes for delete using (auth.uid() = user_id);

create table if not exists public.artwork_reports (
  id bigint generated by default as identity primary key,
  artwork_id bigint not null references public.artworks(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now()
);
alter table public.artwork_reports enable row level security;
drop policy if exists "Users can report artwork" on public.artwork_reports;
create policy "Users can report artwork" on public.artwork_reports for insert with check (auth.uid() = reporter_id);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid references auth.users(id) on delete set null,
  recipient_name text not null,
  sender_name text not null,
  text text not null,
  created_at timestamptz not null default now()
);
alter table public.chat_messages enable row level security;
drop policy if exists "Users can view chat messages" on public.chat_messages;
create policy "Users can view chat messages" on public.chat_messages for select using (auth.uid() = sender_id or auth.uid() = recipient_id);
drop policy if exists "Users can send chat messages" on public.chat_messages;
create policy "Users can send chat messages" on public.chat_messages for insert with check (auth.uid() = sender_id);

do $$
begin
  alter publication supabase_realtime add table public.artworks, public.artwork_likes, public.artist_follows, public.chat_messages;
exception when duplicate_object then null;
end $$;

insert into storage.buckets (id, name, public)
values ('artworks', 'artworks', true)
on conflict (id) do update set public = true;

create policy "Anyone can view artwork images"
on storage.objects for select
using (bucket_id = 'artworks');

create policy "Anyone can upload artwork images"
on storage.objects for insert
with check (bucket_id = 'artworks');
