create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  artist text not null,
  initials text not null,
  title text not null,
  description text not null,
  image text not null,
  price numeric not null default 0,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.artworks enable row level security;
create policy "Anyone can view artworks" on public.artworks for select using (true);
create policy "Anyone can publish artworks" on public.artworks for insert with check (true);

insert into storage.buckets (id, name, public)
values ('artworks', 'artworks', true)
on conflict (id) do update set public = true;

create policy "Anyone can view artwork images"
on storage.objects for select
using (bucket_id = 'artworks');

create policy "Anyone can upload artwork images"
on storage.objects for insert
with check (bucket_id = 'artworks');
