import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useParams } from "react-router-dom";
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, updateProfile, type User } from "firebase/auth";
import { arrayRemove, arrayUnion, collection, doc, increment, onSnapshot, orderBy, query, serverTimestamp, setDoc, runTransaction, Timestamp } from "firebase/firestore";
import { auth, db, isFirebaseConfigured } from "./firebase";
import "./styles.css";

type Profile = { uid: string; displayName: string; email: string; photoURL: string; bio: string; role?: "artist" | "viewer"; createdAt?: Timestamp };
type Post = { id: string; uid: string; displayName: string; photoURL: string; text: string; imageURL?: string; likes?: string[]; likesCount: number; comments?: number; createdAt?: Timestamp; category?: string; location?: string };
type SessionUser = Pick<User, "uid" | "displayName" | "email" | "photoURL">;
type Comment = { id: number; name: string; text: string; avatar: string };

const demoPosts: Post[] = [
  { id: "demo-1", uid: "maya", displayName: "Maya Mokoena", photoURL: "https://i.pravatar.cc/120?img=47", text: "The quiet hour before the city wakes. I’m learning that a painting can hold a conversation without saying everything at once.", imageURL: "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1400&q=85", likesCount: 126, comments: 18, category: "Studio note", location: "Maseru" },
  { id: "demo-2", uid: "thabo", displayName: "Thabo Ndlovu", photoURL: "https://i.pravatar.cc/120?img=12", text: "Found colour in the most unexpected place today. Lesotho keeps reminding me to look closer.", imageURL: "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1400&q=85", likesCount: 84, comments: 9, category: "Field notes", location: "Morija" },
  { id: "demo-3", uid: "amelia", displayName: "Amelia Nkosi", photoURL: "https://i.pravatar.cc/120?img=32", text: "New works from the ‘Home / Elsewhere’ series. For the collectors who believe a wall can carry a memory.", imageURL: "https://images.unsplash.com/photo-1577083552431-6e5fd01988a5?auto=format&fit=crop&w=1400&q=85", likesCount: 210, comments: 31, category: "New work", location: "Maseru" },
];
const artists = [
  ["Maya Mokoena", "Painter · Maseru", "https://i.pravatar.cc/120?img=47", "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=800&q=85"],
  ["Thabo Ndlovu", "Photographer · Morija", "https://i.pravatar.cc/120?img=12", "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=800&q=85"],
  ["Amelia Nkosi", "Mixed media · Maseru", "https://i.pravatar.cc/120?img=32", "https://images.unsplash.com/photo-1577083552431-6e5fd01988a5?auto=format&fit=crop&w=800&q=85"],
];
const initials = (name: string) => name.split(/\s+/).map(x => x[0]).join("").slice(0, 2).toUpperCase() || "PS";
const ago = (value?: Timestamp) => value ? new Intl.RelativeTimeFormat("en", { numeric: "auto" }).format(-Math.max(1, Math.round((Date.now() - value.toMillis()) / 60000)), "minute") : "Just now";

function Avatar({ src, name, size = "avatar-md" }: { src?: string; name: string; size?: string }) {
  return src ? <img src={src} alt="" className={`avatar ${size}`} /> : <div className={`avatar avatar-fallback ${size}`}>{initials(name)}</div>;
}
function Icon({ children }: { children: ReactNode }) { return <span className="icon" aria-hidden="true">{children}</span>; }

function Auth() {
  const [register, setRegister] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); try { if (register) { const result = await createUserWithEmailAndPassword(auth, email, password); await updateProfile(result.user, { displayName: name }); await setDoc(doc(db, "users", result.user.uid), { uid: result.user.uid, displayName: name, email, photoURL: "", bio: "", role: "artist", createdAt: serverTimestamp() }); } else await signInWithEmailAndPassword(auth, email, password); } catch (err) { setError(err instanceof Error ? err.message : "Unable to authenticate"); } };
  return <main className="auth-page"><div className="auth-visual"><div className="brand-lockup"><span className="brand-mark">P</span><span>PAUL SKETCHES</span></div><p className="eyebrow">THE CREATIVE COMMONS OF LESOTHO</p><h1>Make room for <em>what moves you.</em></h1><p className="auth-intro">A living gallery for artists, collectors and curious people building a richer creative culture together.</p><div className="auth-art"><img src="https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=1000&q=85" alt="Colourful abstract artwork" /><span>01 / 03</span></div></div><form onSubmit={submit} className="auth-card"><p className="eyebrow">WELCOME IN</p><h2>{register ? "Begin your practice" : "Return to the room"}</h2><p className="muted">{register ? "Create a profile and share what you’re making." : "Your people and your next spark are here."}</p>{register && <input className="field" required placeholder="Your name" value={name} onChange={e => setName(e.target.value)} />}<input className="field" required type="email" placeholder="Email address" value={email} onChange={e => setEmail(e.target.value)} /><input className="field" required minLength={6} type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} />{error && <p className="error">{error}</p>}<button className="primary wide">{register ? "Create my profile" : "Enter Paul Sketches"} <span>↗</span></button><div className="divider"><span>or</span></div><button type="button" className="text-button" onClick={() => setRegister(!register)}>{register ? "Already part of it? Sign in" : "I’m new here — create an account"}</button><p className="form-note">By joining, you agree to keep this a generous, respectful space.</p></form></main>;
}

function Navbar({ user }: { user: SessionUser }) {
  const [search, setSearch] = useState("");
  return <header className="topbar"><div className="topbar-inner"><Link to="/" className="brand-lockup"><span className="brand-mark">P</span><span className="brand-word">PAUL<br /><i>SKETCHES</i></span></Link><label className="search"><Icon>⌕</Icon><input aria-label="Search artists and work" placeholder="Search artists, work, places..." value={search} onChange={e => setSearch(e.target.value)} /></label><nav className="top-nav" aria-label="Primary navigation"><Link className="nav-link active" to="/">The room</Link><Link className="nav-link" to="/popular">Discover</Link></nav><div className="top-actions"><button className="circle-button" aria-label="Messages">✦</button><button className="circle-button" aria-label="Notifications">♡</button><Link to={`/profile/${user.uid}`} className="profile-chip"><Avatar src={user.photoURL || undefined} name={user.displayName || "You"} size="avatar-sm" /><span>{user.displayName?.split(" ")[0] || "You"}</span></Link><button className="logout" onClick={() => signOut(auth)}>Leave</button></div></div></header>;
}

function LeftSidebar({ profile }: { profile: Profile }) {
  return <aside className="left-sidebar"><div className="sidebar-intro"><span className="eyebrow">YOUR SPACE</span><Link className="sidebar-profile" to={`/profile/${profile.uid}`}><Avatar src={profile.photoURL} name={profile.displayName} /><span><strong>{profile.displayName}</strong><small>View your profile</small></span></Link></div><nav className="side-nav"><Link className="side-item active" to="/"><Icon>◒</Icon><span>The room</span></Link><Link className="side-item" to="/popular"><Icon>✳</Icon><span>Discover artists</span></Link><Link className="side-item" to="/popular"><Icon>⌁</Icon><span>Collections</span></Link><Link className="side-item" to="/popular"><Icon>◎</Icon><span>Events & places</span></Link></nav><div className="sidebar-divider" /><p className="sidebar-label">A little inspiration</p><p className="sidebar-quote">“Art is not what you see, but what you make others see.”<br /><span>— Edgar Degas</span></p><Link to="/popular" className="sidebar-link">Browse the archive <span>↗</span></Link></aside>;
}

function Stories() {
  const stories = [["Your studio", "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=500&q=80"], ["Maya", artists[0][3]], ["Thabo", artists[1][3]], ["Amelia", artists[2][3]]];
  return <section className="stories"><div className="section-heading"><div><span className="eyebrow">FROM THE COMMUNITY</span><h2>Open studios</h2></div><button className="link-button">See all ↗</button></div><div className="story-row">{stories.map(([name, image], index) => <button className="story" key={name}><div className="story-image"><img src={image} alt="" />{index === 0 ? <span className="story-add">＋</span> : <span className="story-live">●</span>}</div><span>{name}</span></button>)}</div></section>;
}

function Composer({ profile, onLocalPost }: { profile: Profile; onLocalPost: (post: Post) => void }) {
  const [text, setText] = useState(""); const [open, setOpen] = useState(false); const [file, setFile] = useState<File>();
  const submit = (e: FormEvent) => { e.preventDefault(); if (!text.trim() && !file) return; onLocalPost({ id: `local-${Date.now()}`, uid: profile.uid, displayName: profile.displayName, photoURL: profile.photoURL, text: text.trim() || "Shared a new work", likesCount: 0, comments: 0, imageURL: file ? URL.createObjectURL(file) : undefined, category: "Studio note" }); setText(""); setFile(undefined); setOpen(false); };
  return <form className="composer" onSubmit={submit}><div className="composer-top"><Avatar src={profile.photoURL} name={profile.displayName} /><button type="button" className="composer-input" onClick={() => setOpen(true)}>What are you making space for?</button></div>{open && <textarea autoFocus className="composer-textarea" placeholder="Share a thought, a work in progress, or a place worth knowing..." value={text} onChange={e => setText(e.target.value)} />}{open && <div className="composer-submit"><span className="muted small">Sharing with the Paul Sketches community</span><button className="primary" type="submit">Publish ↗</button></div>}<div className="composer-options"><label className="composer-option"><Icon>▧</Icon> Share a work<input type="file" accept="image/*" onChange={e => { setFile(e.target.files?.[0]); setOpen(true); }} /></label><button type="button" className="composer-option" onClick={() => setOpen(true)}><Icon>◌</Icon> Studio note</button><button type="button" className="composer-option" onClick={() => setOpen(true)}><Icon>⌁</Icon> Add a place</button></div></form>;
}

function PostCard({ post, uid }: { post: Post; uid: string }) {
  const [liked, setLiked] = useState(post.likes?.includes(uid) || false); const [likes, setLikes] = useState(post.likesCount || 0); const [comments, setComments] = useState<Comment[]>([]); const [comment, setComment] = useState(""); const [showComments, setShowComments] = useState(false);
  const toggle = async () => { setLiked(!liked); setLikes(value => value + (liked ? -1 : 1)); if (!post.id.startsWith("demo-") && !post.id.startsWith("local-")) { const postRef = doc(db, "posts", post.id); await runTransaction(db, async tx => { const snap = await tx.get(postRef); if (!snap.exists()) return; const data = snap.data() as Post; const isLiked = (data.likes || []).includes(uid); tx.update(postRef, { likes: isLiked ? arrayRemove(uid) : arrayUnion(uid), likesCount: increment(isLiked ? -1 : 1) }); }); } };
  const addComment = (e: FormEvent) => { e.preventDefault(); if (!comment.trim()) return; setComments(value => [...value, { id: Date.now(), name: "You", text: comment.trim(), avatar: "" }]); setComment(""); setShowComments(true); };
  return <article className="post"><div className="post-header"><Avatar src={post.photoURL} name={post.displayName} /><div className="post-author"><Link to={`/profile/${post.uid}`}><strong>{post.displayName}</strong></Link><span>{post.category} · {post.location || "Lesotho"} · {ago(post.createdAt)}</span></div><button className="more-button" aria-label="More options">•••</button></div>{post.text && <p className="post-copy">{post.text}</p>}{post.imageURL && <img className="post-image" src={post.imageURL} alt={post.category || "Shared artwork"} />}{(likes > 0 || comments.length > 0) && <div className="post-stats"><span><b className="reaction-dot">✦</b> {likes} appreciations</span><button onClick={() => setShowComments(!showComments)}>{comments.length || post.comments || 0} notes</button></div>}<div className="post-actions"><button className={liked ? "liked" : ""} onClick={toggle}><Icon>{liked ? "✦" : "♡"}</Icon> Appreciate</button><button onClick={() => setShowComments(!showComments)}><Icon>◌</Icon> Leave a note</button><button onClick={() => navigator.clipboard?.writeText(window.location.href)}><Icon>↗</Icon> Share</button></div>{showComments && <div className="comments"><div className="comment-list">{comments.map(item => <div className="comment" key={item.id}><Avatar src={item.avatar || undefined} name={item.name} size="avatar-sm" /><div><strong>{item.name}</strong><p>{item.text}</p></div></div>)}</div><form className="comment-form" onSubmit={addComment}><Avatar name="You" size="avatar-sm" /><input aria-label="Write a note" placeholder="Leave a thoughtful note..." value={comment} onChange={e => setComment(e.target.value)} /></form></div>}</article>;
}

function RightSidebar() {
  return <aside className="right-sidebar"><div className="aside-block feature-block"><span className="eyebrow">THIS WEEK</span><h2>What’s on<br /><em>in Maseru</em></h2><p>Exhibitions, open studios and the people making the city glow.</p><Link to="/popular" className="outline-button">Explore the guide ↗</Link></div><div className="aside-block"><div className="section-heading"><h2>People to know</h2><button className="link-button">View all</button></div><div className="contacts">{artists.map(([name, role, photo]) => <Link className="contact" to="/popular" key={name}><Avatar src={photo} name={name} size="avatar-sm" /><span><strong>{name}</strong><small>{role}</small></span><b>＋</b></Link>)}</div></div><div className="aside-block prompt-block"><span className="eyebrow">A QUESTION FOR YOU</span><p>What place in Lesotho makes you want to create?</p><button className="link-button">Share your answer ↗</button></div></aside>;
}

function Feed({ user }: { user: SessionUser }) {
  const [profile, setProfile] = useState<Profile>(); const [posts, setPosts] = useState<Post[]>(demoPosts); const [loading, setLoading] = useState(true);
  useEffect(() => { const unsub = onSnapshot(doc(db, "users", user.uid), snap => { const data = snap.data() as Profile | undefined; setProfile(data || { uid: user.uid, displayName: user.displayName || "You", email: user.email || "", photoURL: user.photoURL || "", bio: "" }); setLoading(false); }, () => { setProfile({ uid: user.uid, displayName: user.displayName || "You", email: user.email || "", photoURL: user.photoURL || "", bio: "" }); setLoading(false); }); return unsub; }, [user]);
  useEffect(() => { if (!isFirebaseConfigured) return; return onSnapshot(query(collection(db, "posts"), orderBy("createdAt", "desc")), snap => { if (snap.docs.length) setPosts(snap.docs.map(d => ({ id: d.id, ...d.data() } as Post))); }, () => undefined); }, []);
  if (loading || !profile) return <div className="loading">Opening the room…</div>;
  return <><Navbar user={user} /><div className="app-layout"><LeftSidebar profile={profile} /><main className="feed"><div className="feed-heading"><div><span className="eyebrow">FRIDAY, 18 SEPTEMBER 2026</span><h1>Good morning, {profile.displayName.split(" ")[0]} <span>✦</span></h1><p className="muted">A few good things from your creative neighbourhood.</p></div><button className="filter-button">Latest <span>⌄</span></button></div><Stories /><Composer profile={profile} onLocalPost={post => setPosts(value => [post, ...value])} />{posts.map(post => <PostCard key={post.id} post={post} uid={user.uid} />)}</main><RightSidebar /></div></>;
}

function PopularArtists({ user }: { user: SessionUser }) {
  const rankings = useMemo(() => demoPosts, []);
  return <><Navbar user={user} /><main className="discovery"><div className="discovery-heading"><div><span className="eyebrow">THE PAUL SKETCHES INDEX</span><h1>Find your next <em>favourite.</em></h1><p className="muted">Artists, makers and storytellers shaping the creative language of Lesotho.</p></div><button className="filter-button">All disciplines <span>⌄</span></button></div><div className="artist-grid">{rankings.map((artist, index) => <article className="artist-card" key={artist.id}><img src={artist.imageURL} alt="" /><div className="artist-info"><span className="rank">0{index + 1}</span><Avatar src={artist.photoURL} name={artist.displayName} size="avatar-lg" /><h2>{artist.displayName}</h2><p className="muted">{artist.category} · {artist.location}</p><p className="artist-bio">{artist.text}</p><Link className="outline-button" to={`/profile/${artist.uid}`}>View profile ↗</Link></div></article>)}</div></main></>;
}

function ProfilePage({ user }: { user: SessionUser }) { const { uid } = useParams(); const own = uid === user.uid; return <><Navbar user={user} /><main className="profile-page"><div className="profile-cover" /><div className="profile-card"><Avatar name={own ? user.displayName || "You" : "Community member"} size="avatar-xl" /><span className="eyebrow">ARTIST PROFILE</span><h1>{own ? user.displayName : "Community member"}</h1><p className="muted">Sharing ideas, moments, and creative work from the highlands.</p><button className="primary">{own ? "Edit profile" : "Follow artist"} <span>↗</span></button></div></main></>; }
function App() {
  const demoUser: SessionUser = { uid: "demo-user", displayName: "Alex Morgan", email: "demo@example.com", photoURL: "" };
  const [user, setUser] = useState<SessionUser | null | undefined>(isFirebaseConfigured ? undefined : demoUser);
  useEffect(() => isFirebaseConfigured ? onAuthStateChanged(auth, setUser) : undefined, []);
  if (user === undefined) return <div className="loading">Loading Paul Sketches…</div>;
  if (!user) return <Auth />;
  return <><div className="demo-banner">Preview mode · Connect Firebase to make this room your own.</div><Routes><Route path="/profile/:uid" element={<ProfilePage user={user} />} /><Route path="/popular" element={<PopularArtists user={user} />} /><Route path="*" element={<Feed user={user} />} /></Routes></>;
}
createRoot(document.getElementById("root")!).render(<BrowserRouter><App /></BrowserRouter>);
